name: Flama Final

on:
  pull_request:
    branches: [main]

permissions:
  contents: read

jobs:
  final:
    uses: maxbec/flama-delivery-platform/.github/workflows/reusable-final.yml@e72d73ea4f6bcedb62b333026b2567bfc0cb4ef5
    with:
      base-sha: ${{ github.event.pull_request.base.sha }}
      head-sha: ${{ github.event.pull_request.head.sha }}
      platform-sha: e72d73ea4f6bcedb62b333026b2567bfc0cb4ef5
